services:
  smartdocanalyzer-api:
    container_name: smartdocanalyzer-api
    build:
      context: .
      dockerfile: SmartDocAnalyzer.API/Dockerfile
    ports:
      - "5000:80"       # HTTP
      - "5001:443"      # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
